/**
 * GhostNote theme for Lexical editor
 * Styled to match the existing GhostNote UI
 */

import type { EditorThemeClasses } from 'lexical';

const theme: EditorThemeClasses = {
  characterLimit: 'editor-character-limit',
  code: 'editor-code bg-ghost-dark/60 text-ghost-neon font-mono p-1 rounded',
  codeHighlight: {
    atrule: 'editor-token-attr',
    attr: 'editor-token-attr',
    boolean: 'editor-token-boolean',
    builtin: 'editor-token-builtin',
    cdata: 'editor-token-cdata',
    char: 'editor-token-char',
    class: 'editor-token-class',
    'class-name': 'editor-token-class-name',
    comment: 'editor-token-comment text-gray-500',
    constant: 'editor-token-constant',
    deleted: 'editor-token-deleted',
    doctype: 'editor-token-doctype',
    entity: 'editor-token-entity',
    function: 'editor-token-function text-ghost-neon',
    important: 'editor-token-important',
    inserted: 'editor-token-inserted',
    keyword: 'editor-token-keyword text-ghost-purple',
    namespace: 'editor-token-namespace',
    number: 'editor-token-number text-blue-400',
    operator: 'editor-token-operator',
    prolog: 'editor-token-prolog',
    property: 'editor-token-property',
    punctuation: 'editor-token-punctuation text-gray-300',
    regex: 'editor-token-regex',
    selector: 'editor-token-selector',
    string: 'editor-token-string text-green-400',
    symbol: 'editor-token-symbol',
    tag: 'editor-token-tag',
    url: 'editor-token-url',
    variable: 'editor-token-variable',
  },
  embedBlock: {
    base: 'editor-embed-block',
    focus: 'editor-embed-block-focus',
  },
  hashtag: 'editor-hashtag text-ghost-purple hover:text-ghost-neon cursor-pointer',
  heading: {
    h1: 'editor-heading-h1 text-3xl font-bold text-white mb-4 mt-6',
    h2: 'editor-heading-h2 text-2xl font-semibold text-white mb-3 mt-5',
    h3: 'editor-heading-h3 text-xl font-semibold text-white mb-2 mt-4',
    h4: 'editor-heading-h4 text-lg font-medium text-white mb-2 mt-3',
    h5: 'editor-heading-h5 text-base font-medium text-white mb-1 mt-2',
    h6: 'editor-heading-h6 text-sm font-medium text-white mb-1 mt-2',
  },
  image: 'editor-image max-w-full h-auto rounded-lg shadow-lg',
  indent: 'editor-indent-1 ml-8',
  inlineImage: 'inline-editor-image max-w-full h-auto',
  link: 'editor-link text-ghost-neon hover:text-ghost-purple underline cursor-pointer transition-colors duration-200',
  list: {
    listitem: 'editor-listitem mb-1',
    listitemChecked: 'editor-listitem-checked',
    listitemUnchecked: 'editor-listitem-unchecked',
    nested: {
      listitem: 'editor-nested-listitem',
    },
    ol: 'editor-list-ol list-decimal ml-6 space-y-1',
    ul: 'editor-list-ul list-disc ml-6 space-y-1',
  },
  ltr: 'ltr',
  mark: 'editor-mark bg-yellow-400 text-black px-1 rounded',
  markOverlap: 'editor-mark-overlap',
  paragraph: 'editor-paragraph text-white leading-relaxed mb-3',
  placeholder: 'editor-placeholder text-gray-500 pointer-events-none absolute top-0 left-0',
  quote: 'editor-quote border-l-4 border-ghost-purple pl-4 italic text-gray-300 bg-ghost-dark/30 py-2 my-4',
  rtl: 'rtl',
  table: 'editor-table border-collapse border border-ghost-purple/30 my-4',
  tableAddColumns: 'editor-table-add-columns',
  tableAddRows: 'editor-table-add-rows',
  tableCell: 'editor-table-cell border border-ghost-purple/20 p-2 bg-ghost-dark/50',
  tableCellActionButton: 'editor-table-cell-action-button',
  tableCellActionButtonContainer: 'editor-table-cell-action-button-container',
  tableCellEditing: 'editor-table-cell-editing',
  tableCellHeader: 'editor-table-cell-header bg-ghost-purple/20 font-semibold',
  tableCellPrimarySelected: 'editor-table-cell-primary-selected bg-ghost-purple/30',
  tableCellResizer: 'editor-table-cell-resizer',
  tableCellSelected: 'editor-table-cell-selected bg-ghost-purple/10',
  tableCellSortedIndicator: 'editor-table-cell-sorted-indicator',
  tableResizeRuler: 'editor-table-resize-ruler',
  tableSelected: 'editor-table-selected',
  tableSelection: 'editor-table-selection',
  text: {
    bold: 'editor-text-bold font-bold',
    code: 'editor-text-code bg-ghost-dark/60 text-ghost-neon font-mono px-1 py-0.5 rounded text-sm',
    hashtag: 'editor-text-hashtag text-ghost-purple',
    italic: 'editor-text-italic italic',
    strikethrough: 'editor-text-strikethrough line-through',
    subscript: 'editor-text-subscript',
    superscript: 'editor-text-superscript',
    underline: 'editor-text-underline underline',
    underlineStrikethrough: 'editor-text-underline-strikethrough underline line-through',
  },
};

export default theme;
